namespace SatLight.Enums
{
    public enum SatCategory
    {
        All = 0,
        ANY,
        AmateurRadio = 18,
        BeidouNavigationSystem = 35,
        Brightest = 1,
        Celestis = 45,
        ChineseSpaceStation = 54,
        CubeStats = 32,
        DisasterMonitoring = 8,
        EarthResources = 6,
        Education = 29,
        Engineering = 28,
        Experimental = 19,
        Flock = 48,
        Galileo = 22,
        Geodetic = 27,
        Geostationary = 10,
        GlobalPositioningSystemConstellation = 50,
        GlobalPositioningSystemOperational = 20,
        Globalstart = 17,
        GlonassCosntellation = 51,
        GlonassOperational = 21,
        GOES = 5,
        Gontes = 40,
        Gorizont = 12,
        Instelsat = 11,
        Iridium = 15,
        IRNSS = 46,
        ISS = 2,
        Lemur = 49,
        Military = 30,
        Molniya = 14,
        NavyNavigationSatelliteSystem = 24,
        NOAA = 4,
        O3BNetworks = 43,
        OneWeb = 53,
        Orbcomm = 16,
        Parus = 38,
        QZSS = 47,
        RadarCalibration = 31,
        Raduga = 13,
        RussianLEONavigation = 25,
        SatelliteBasedAugmentationSystem = 23,
        SearchAndRescue = 7,
        SpaceAndEarthScience = 26,
        Starlink = 52,
        Strela = 39,
        TrackingAndDataRelaySatelliteSystem = 9,
        Tselina = 44,
        Tsikada = 42,
        Tsiklon = 41,
        TV = 34,
        Weather = 3,
        WestfordNeedles = 37,
        XMAndSirius = 33,
        Yaogan = 36
    }
}